### ISSUE TITLE
Hide lines when inactive

### ISSUE THREAD

**Issue by fvgarrel** [reptilex/tesla-style-solar-power-card#23] opened 2020-12-10 10:53 UTC
Is it possible that you hide the lines as soon as there is no more transfer on this path?

**Comment by reptilex** [comment] 2020-12-10 11:32
I did a quick implementation of it, currently it's not the default, althhough I'm thinking it maybe shoud. Add "hide_inactive_lines" in the card config and set it to 1. Then you will have only active lines.

**Comment by fvgarrel** [comment] 2020-12-10 11:39
Cool, thanks for the quick implementation and response, I love it :) 
![tesla](https://user-images.githubusercontent.com/54435038/101767603-b9420c00-3ae4-11eb-84f7-8195c43a3638.PNG)
![homeass](https://user-images.githubusercontent.com/54435038/101767606-ba733900-3ae4-11eb-9169-6b0c1a0c2f51.PNG)

**Comment by DRAGandDROP** [comment] 2020-12-10 16:24
when enabling the feature the "points" do not move anylonger. only the line is visible. Is it a feature or a bug? ;)
![image](https://user-images.githubusercontent.com/4682105/101799558-9592bc00-3b0c-11eb-8d5c-ebd0fa5ca8e7.png)

**Comment by PierreScerri** [comment] 2020-12-10 17:53
Hide inactive lines has frozen the dot motion

**Comment by PierreScerri** [comment] 2020-12-10 18:02
Dots were moving with 9.1.2 and show_w_not_kw:1
Dots stopped moving with 9.2.1 and show_w_not_kw:1

**Comment by msim888** [comment] 2020-12-10 19:20
There is an error in 9.2.1

The speed variable is wrong

The last a few rows have to be:


```
  getSpeed(value) {
    var speed = 0;
    
    if (value > 0 && this.w_or_kw !== 'W') {
      speed = 0.07 * value;
    } else if (value > 0 && this.w_or_kw === 'W') {
      speed = 0.00007 * value;
    }
    
    return speed;
  }
}
```

customElements.define('tesla-style-solar-power-card', TeslaStyleSolarPowerCard);

Then everything works very well:

![image](https://user-images.githubusercontent.com/73604538/101819125-7ce6ce00-3b2d-11eb-962d-29c2da56cc2c.png)

**Comment by msim888** [comment] 2020-12-10 19:33
But I have another issue:

![image](https://user-images.githubusercontent.com/73604538/101820403-3eeaa980-3b2f-11eb-82b3-fdc3266e63b2.png)

There is solar circle even it the solar power is 0

**Comment by fvgarrel** [comment] 2020-12-10 19:34
> But I have another issue:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/73604538/101820403-3eeaa980-3b2f-11eb-82b3-fdc3266e63b2.png)
> 
> 
> 
> There is solar circle even it the solar power is 0

Because your battery is charging.

**Comment by msim888** [comment] 2020-12-10 19:46
Yeah, but it is charging only from grid, not from sun - it's night here.

**Comment by fvgarrel** [comment] 2020-12-10 19:48
> Yeah, but it is charging only from grid, not from sun - it's night here.

Yes. The Solar to Battery Path is activated when the battery is loading. Maybe the Code should look from where the energy is coming.

**Comment by msim888** [comment] 2020-12-10 20:05
Oh, I see, Thanks, fvgarrel!

**Comment by LanceMcCarthy** [comment] 2020-12-11 00:47
Hiding the lines when not active is the behavior of the Tesla app. However, I do not think this should be the default for the card. Let me expain... 

If the default for the card was to hide them, the the user wouldn't know if a missing line was due to an incorrect configuration or it is working as expected

Therefore, my vote is to show lines by default.

That said, you can add a note at the end of the Getting Started steps to set the "HideLines property once everything is confirmed working".


> if you do make hiding the lines the default behavior, please show an error state (i.e.  dotted red line for an incorrectly configured setting)

**Comment by msim888** [comment] 2020-12-11 05:33
Totally agree with LanceMcCarthy.
My vote is to show lines by default too.

**Comment by reptilex** [comment] 2020-12-11 08:25
I somehow overwrote the speed changes for the w_not_kw behaviour, very sorry and thanks for raising the issue. It should be online, but I have not yet created a new release. Will do so as soon as I have figured out the issue with the charging line duplication when charging from grid. I have created another issue for that @msim888 can you follow that one, I have some questions there.
On the bright side, all but those lines work so I will see this as a feature finish state and close the issue.

**Closed by reptilex** 2020-12-11 08:25 UTC
Labels: enhancement
